using Volo.Abp;

namespace NewtonsoftJsonSerializerBug.EntityFrameworkCore;

public abstract class NewtonsoftJsonSerializerBugEntityFrameworkCoreTestBase : NewtonsoftJsonSerializerBugTestBase<NewtonsoftJsonSerializerBugEntityFrameworkCoreTestModule>
{

}
