namespace NewtonsoftJsonSerializerBug;

public abstract class NewtonsoftJsonSerializerBugApplicationTestBase : NewtonsoftJsonSerializerBugTestBase<NewtonsoftJsonSerializerBugApplicationTestModule>
{

}
